# Generated by Django 4.1.6 on 2023-02-17 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "leave_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Privilege_Leave"),
                            (2, "Casual_Leave"),
                            (3, "Sick_Leave"),
                        ],
                        default=3,
                        null=True,
                    ),
                ),
                ("reason", models.TextField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("leave_days", models.IntegerField()),
                (
                    "leave_status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Pending"), (1, "Approved"), (2, "Reject")],
                        default="Pending",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
