# Generated by Django 4.1.6 on 2023-02-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaveRequest", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leaverequest", old_name="user_id", new_name="user_name",
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_status",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(0, "Pending"), (1, "Approved"), (2, "Reject")],
                default=0,
                null=True,
            ),
        ),
    ]
